Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine(">>> I'm printing in green <<<");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine(">>> I'm printing in blue <<<");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine(">>> I'm printing in red <<<");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Cyan;
Console.WriteLine(">>> I'm printing in Cyan <<<");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine(">>> I'm printing in Yellow <<<");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine(">>> I'm printing in Dark Red <<<");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine(">>> I'm printing in Magenta <<<");
Console.ResetColor();